using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NuGet.Frameworks;
using NuGet.Packaging;
using NuGet.Packaging.Core;
using NuGet.Packaging.Licenses;
using NuGet.Versioning;

namespace Twinpack.Protocol
{
    public class NugetPackFile
    {
        /// <summary>Absolute or working-directory-relative path of the file to put into the package.</summary>
        public string Source { get; set; }

        /// <summary>
        /// Folder inside the package, e.g. <c>TC3.1</c>. Empty puts the file in the package root.
        /// Corresponds to the <c>target</c> attribute of a nuspec <c>&lt;file&gt;</c> element.
        /// </summary>
        public string Target { get; set; }
    }

    public class NugetPackDependency
    {
        public string Id { get; set; }

        /// <summary>
        /// TwinCAT version of the dependency, or <c>*</c>/empty for "any version". Translated to a
        /// NuGet version range the same way the package's own version is translated.
        /// </summary>
        public string Version { get; set; }
    }

    public class NugetPackRequest
    {
        public string Id { get; set; }
        public string Version { get; set; }
        public string Title { get; set; }
        public string Authors { get; set; }
        public string Description { get; set; }
        public string Copyright { get; set; }
        public string ProjectUrl { get; set; }

        /// <summary>SPDX license expression. Ignored with a warning if it is not valid SPDX.</summary>
        public string License { get; set; }

        /// <summary>License file to embed, used instead of <see cref="License"/> when set.</summary>
        public string LicenseFile { get; set; }

        /// <summary>Icon to embed, shown in the Twinpack catalog instead of an autogenerated one.</summary>
        public string IconFile { get; set; }

        public IEnumerable<string> Tags { get; set; }
        public IEnumerable<NugetPackDependency> Dependencies { get; set; }
        public IEnumerable<NugetPackFile> Files { get; set; }
        public string OutputDirectory { get; set; }
    }

    /// <summary>
    /// Writes a .nupkg for a TwinCAT library or application. This is the write side of
    /// <see cref="NugetServer"/>: what it produces is what <see cref="NugetServer"/> and the
    /// Beckhoff repository can consume again, so the two have to stay in step - in particular a
    /// library package must contain exactly one .library or .compiled-library file, and a compiled
    /// library has to carry the <c>tp-compiled-library</c> tag for the reader to recognize it.
    /// </summary>
    public static class NugetPackBuilder
    {
        private static readonly NLog.Logger _logger = NLog.LogManager.GetCurrentClassLogger();

        /// <summary>
        /// NuGet package ids allow no spaces, so a library title like <c>My Library</c> becomes
        /// <c>My.Library</c>. The real title is kept in the package's <c>title</c>, which is what
        /// Twinpack matches against the TwinCAT library title.
        /// </summary>
        public static string PackageId(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                return "package";

            var sanitized = new string(name.Select(c =>
                (char.IsLetterOrDigit(c) && c < 128) || c == '_' || c == '.' || c == '-' ? c : '.').ToArray());

            while (sanitized.Contains(".."))
                sanitized = sanitized.Replace("..", ".");

            sanitized = sanitized.Trim('.');

            return sanitized.Length == 0 ? "package" : sanitized;
        }

        /// <summary>Writes the package and returns the path of the .nupkg that was written.</summary>
        public static string Pack(NugetPackRequest request)
        {
            if (request == null)
                throw new ArgumentNullException(nameof(request));

            var id = PackageId(request.Id);
            var version = Core.AutomationInterface.NugetVersion(request.Version);
            if (!NuGetVersion.TryParse(version, out var nugetVersion))
                throw new ArgumentException($"'{request.Version}' is not a version a NuGet package can be published under");

            var metadata = new ManifestMetadata
            {
                Id = id,
                Version = nugetVersion,
                Title = string.IsNullOrWhiteSpace(request.Title) ? request.Id : request.Title,
                Authors = new[] { string.IsNullOrWhiteSpace(request.Authors) ? id : request.Authors },
                Description = FirstNonEmpty(request.Description, request.Title, request.Id),
                Copyright = request.Copyright,
                Tags = string.Join(" ", (request.Tags ?? Enumerable.Empty<string>()).Where(x => !string.IsNullOrWhiteSpace(x)).ToArray()),
                DependencyGroups = DependencyGroups(request.Dependencies)
            };

            if (!string.IsNullOrWhiteSpace(request.ProjectUrl) && Uri.TryCreate(request.ProjectUrl, UriKind.Absolute, out var projectUrl))
                metadata.SetProjectUrl(projectUrl.ToString());

            var builder = new PackageBuilder();
            builder.Populate(metadata);

            foreach (var file in request.Files ?? Enumerable.Empty<NugetPackFile>())
            {
                if (string.IsNullOrWhiteSpace(file?.Source))
                    continue;

                var source = Path.GetFullPath(file.Source);
                if (!File.Exists(source))
                    throw new FileNotFoundException($"Cannot pack '{source}' into {id}, the file does not exist", source);

                builder.Files.Add(new PhysicalPackageFile
                {
                    SourcePath = source,
                    TargetPath = string.IsNullOrWhiteSpace(file.Target)
                        ? Path.GetFileName(source)
                        : $"{file.Target.Trim('/', '\\')}/{Path.GetFileName(source)}"
                });
            }

            ApplyLicense(builder, request);
            ApplyIcon(builder, request);

            var outputDirectory = string.IsNullOrWhiteSpace(request.OutputDirectory)
                ? Directory.GetCurrentDirectory()
                : Path.GetFullPath(request.OutputDirectory);
            Directory.CreateDirectory(outputDirectory);

            // Same file name as `nuget pack` gives it, so a package built here is indistinguishable
            // from one built by the manual nuspec route it replaces.
            var path = Path.Combine(outputDirectory, $"{id}.{nugetVersion.ToNormalizedString()}.nupkg");
            using (var stream = File.Create(path))
            {
                builder.Save(stream);
            }

            _logger.Info("[pack] {0} {1} -> {2}", id, nugetVersion.ToNormalizedString(), path);

            return path;
        }

        static List<PackageDependencyGroup> DependencyGroups(IEnumerable<NugetPackDependency> dependencies)
        {
            var packageDependencies = (dependencies ?? Enumerable.Empty<NugetPackDependency>())
                .Where(x => !string.IsNullOrWhiteSpace(x?.Id))
                .GroupBy(x => PackageId(x.Id), StringComparer.OrdinalIgnoreCase)
                .Select(g => new PackageDependency(g.Key, DependencyRange(g.First().Version)))
                .ToList();

            return packageDependencies.Count == 0
                ? new List<PackageDependencyGroup>()
                : new List<PackageDependencyGroup> { new PackageDependencyGroup(NuGetFramework.AnyFramework, packageDependencies) };
        }

        static VersionRange DependencyRange(string version)
        {
            var nuget = Core.AutomationInterface.NugetVersion(version);
            if (string.IsNullOrWhiteSpace(nuget) || nuget == "*" || !NuGetVersion.TryParse(nuget, out var parsed))
                return VersionRange.All;

            // A bare version in a nuspec means "this version or newer", which is what a TwinCAT
            // library reference resolves to as well.
            return new VersionRange(parsed);
        }

        static void ApplyLicense(PackageBuilder builder, NugetPackRequest request)
        {
            if (!string.IsNullOrWhiteSpace(request.LicenseFile))
            {
                var source = Path.GetFullPath(request.LicenseFile);
                if (!File.Exists(source))
                    throw new FileNotFoundException($"License file '{source}' does not exist", source);

                var fileName = Path.GetFileName(source);
                builder.Files.Add(new PhysicalPackageFile { SourcePath = source, TargetPath = fileName });
                builder.LicenseMetadata = new LicenseMetadata(LicenseType.File, fileName, null, null, LicenseMetadata.EmptyVersion);
                return;
            }

            if (string.IsNullOrWhiteSpace(request.License))
                return;

            // Zeugwerk license identifiers such as ZF1000 are not SPDX. The parser accepts them as
            // non-standard identifiers, but NuGet clients reject a package that carries one, so
            // leave the license out and say why instead of producing an unusable package.
            try
            {
                var expression = NuGetLicenseExpression.Parse(request.License);
                if (!expression.HasOnlyStandardIdentifiers())
                {
                    _logger.Warn("[pack] '{0}' is not a standard SPDX license identifier, omitting it from {1}", request.License, builder.Id);
                    return;
                }

                builder.LicenseMetadata = new LicenseMetadata(LicenseType.Expression, request.License, expression, null, LicenseMetadata.EmptyVersion);
            }
            catch (Exception ex)
            {
                _logger.Warn("[pack] '{0}' is not a valid SPDX license expression, omitting it from {1} ({2})", request.License, builder.Id, ex.Message);
            }
        }

        static void ApplyIcon(PackageBuilder builder, NugetPackRequest request)
        {
            if (string.IsNullOrWhiteSpace(request.IconFile))
                return;

            var source = Path.GetFullPath(request.IconFile);
            if (!File.Exists(source))
                throw new FileNotFoundException($"Icon file '{source}' does not exist", source);

            var fileName = Path.GetFileName(source);
            builder.Files.Add(new PhysicalPackageFile { SourcePath = source, TargetPath = fileName });
            builder.Icon = fileName;
        }

        static string FirstNonEmpty(params string[] values)
        {
            return values.FirstOrDefault(x => !string.IsNullOrWhiteSpace(x));
        }
    }
}
