name: Pull
on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:
jobs:
  Pull:
    runs-on: windows-latest
    steps:
      - run: |
          curl.exe -s -o twinpack-registry-latest.tar.gz https://zeugwerk.dev/Tools/twinpack-registry-latest.tar.gz
          tar -xf twinpack-registry-latest.tar.gz
          ./twinpack-registry.exe push --username "${{ secrets.ACTIONS_ZGWK_USERNAME }}" --password "${{ secrets.ACTIONS_ZGWK_PASSWORD }}"
        shell: bash
