name: Pull
on:
  schedule:
    - cron: "5 13 * * *"
  workflow_dispatch:
jobs:
  Pull:
    runs-on: windows-latest
    steps:
      - name: Pull Twinpack Registry
        env:
          ACTIONS_ZGWK_USERNAME: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
          ACTIONS_ZGWK_PASSWORD: ${{ secrets.ACTIONS_ZGWK_PASSWORD }}
          ACTIONS_BECKHOFF_USERNAME: ${{ secrets.ACTIONS_BECKHOFF_USERNAME }}
          ACTIONS_BECKHOFF_PASSWORD: ${{ secrets.ACTIONS_BECKHOFF_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl.exe -s -o twinpack-registry-latest.tar.gz https://zeugwerk.dev/Tools/twinpack-registry-latest.tar.gz
          tar -xf twinpack-registry-latest.tar.gz
          ./twinpack-registry.exe pull \
            --username "$ACTIONS_ZGWK_USERNAME" \
            --password "$ACTIONS_ZGWK_PASSWORD" \
            --beckhoff-username "$ACTIONS_BECKHOFF_USERNAME" \
            --beckhoff-password "$ACTIONS_BECKHOFF_PASSWORD" \
            --token "$GH_TOKEN"
        shell: bash
